// NOTE: this file is auto-generated by Construct
declare namespace InstanceType {
	class Question_1 extends IDictionaryInstance {
		instVars: {
			text: string,
			reponse_1: number,
			response_2: number
		};
	}
	class Dictionary extends IDictionaryInstance {
		instVars: {
			text: string
		};
	}

}