// NOTE: this file is auto-generated by Construct
declare class IConstructProjectObjects {
	readonly Question_1: IObjectType<InstanceType.Question_1>;
	readonly Dictionary: IObjectType<InstanceType.Dictionary>;
}